#ifndef METADATA_H
#define METADATA_H

struct Metadata
{
    unsigned long id;

// Note:
// It is possible to generate signatures for both pointer and the ID.
// The signature for the pointer can be generated by PACIA instruction
// and for the ID can be generated by PACGA instruction as follow.
// This trick is pretty useful to implement a more robust backward search.

//    int id;
//    int id_signature;

//    Signature generation for ID
//    meta->id_signature = __pacga(id,(long)meta);

};

#endif
